import { BRAND } from "@/lib/constants/brand";

export interface Variant {
  id: string;
  sku: string;
  title: string;
  colorName: string;
  colorHex: string;
  materialName?: string;
  sizeName?: string;
  price: number;
  compareAtPrice?: number;
  inventory: number;
  isDefault: boolean;
  images: string[];
}

export interface ReviewItem {
  id: string;
  authorName: string;
  rating: number;
  title: string;
  body: string;
  createdAt: string;
  verified: boolean;
}

export interface ProductItem {
  id: string;
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  details: string;
  materialsInfo: string;
  dimensionsInfo: string;
  capacityInfo: string;
  careInfo: string;
  basePrice: number;
  compareAtPrice?: number;
  currency: string;
  categorySlug: string;
  categoryName: string;
  subcategorySlug?: string;
  collections: string[];
  tags: string[];
  rating: number;
  reviewCount: number;
  isBestseller?: boolean;
  isNewRelease?: boolean;
  isFeatured?: boolean;
  isBundle?: boolean;
  isComingSoon?: boolean;
  isSoldOut?: boolean;
  primaryImage: string;
  hoverImage: string;
  images: string[];
  variants: Variant[];
  reviews: ReviewItem[];
}

export interface CategoryItem {
  id: string;
  name: string;
  slug: string;
  description: string;
  image?: string;
  subcategories: { name: string; slug: string }[];
}

export interface CollectionItem {
  id: string;
  name: string;
  slug: string;
  title: string;
  subtitle: string;
  editorialHeader: string;
  heroImage: string;
  productSlugs: string[];
}

export const CATEGORIES: CategoryItem[] = [
  {
    id: "cat_balms",
    name: "Soothing Balms & Pain Relief",
    slug: "soothing-balms",
    description: "Authentic imported herbal balms, Thai liniments, soothing rubs, and aromatic inhalers.",
    image: "https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg",
    subcategories: [
      { name: "Herbal Balms", slug: "herbal-balms" },
      { name: "Liniments & Oils", slug: "liniments" },
      { name: "Inhalers & Roll-ons", slug: "inhalers" },
    ],
  },
  {
    id: "cat_hair_oils",
    name: "Hair Oils & Scalp Care",
    slug: "hair-oils",
    description: "Pure Jamaican black castor oil, organic Ceylon virgin coconut, and restorative scalp therapy formulas.",
    image: "https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg",
    subcategories: [
      { name: "Castor Oils", slug: "castor-oils" },
      { name: "Coconut Oils", slug: "coconut-oils" },
      { name: "Shampoos & Conditioners", slug: "shampoos" },
    ],
  },
  {
    id: "cat_essential_oils",
    name: "Essential Oils & Pure Wellness",
    slug: "essential-oils",
    description: "Spanish cold-pressed extra virgin olive oils, pure seed oils, and botanical wellness extracts.",
    image: "https://valobazar.com/storage/products/IPtpJty2TlYmwuE0zKImon5ALBWLFl5Y2Dp2Psde.jpg",
    subcategories: [
      { name: "Spanish Olive Oils", slug: "olive-oils" },
      { name: "Cold-Pressed Seed Oils", slug: "seed-oils" },
      { name: "Wellness Extracts", slug: "wellness" },
    ],
  },
  {
    id: "cat_skincare",
    name: "Herbal & Winter Skin Care",
    slug: "herbal-skincare",
    description: "Authentic Kojic soaps, hydrating body lotions, daily facial cleansers, and barrier-protecting jellies.",
    image: "https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg",
    subcategories: [
      { name: "Soaps & Cleansers", slug: "cleansers" },
      { name: "Body Lotions", slug: "lotions" },
      { name: "Moisturizers & Jellies", slug: "creams" },
    ],
  },
];

export const COLLECTIONS: CollectionItem[] = [
  {
    id: "col_pain_relief",
    name: "Pain Relief & Thermal Comfort",
    slug: "pain-relief-thermal",
    title: "Instant Soothing & Muscular Comfort",
    subtitle: "Fast-acting herbal balms, roll-on liniments, and menthol vapor rubs",
    editorialHeader: "Time-tested herbal extracts and camphor blends designed for instant muscle relaxation.",
    heroImage: "https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg",
    productSlugs: [
      "crocodile-balm-50g-thailand",
      "siam-tiger-balm-50g",
      "green-seven-lemongrass-balm-50g",
      "omega-pain-killer-liniment-60ml",
      "axe-brand-universal-oil-56ml",
    ],
  },
  {
    id: "col_hair_growth",
    name: "Pure Hair Growth & Scalp Therapy",
    slug: "hair-growth-scalp",
    title: "Dense Scalp Therapy & Deep Nourishment",
    subtitle: "Original Jamaican black castor, Ceylon extra virgin coconut, and botanical cleansers",
    editorialHeader: "Rich in ricinoleic acid and essential fatty acids to stimulate follicles and restore natural shine.",
    heroImage: "https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg",
    productSlugs: [
      "jamaican-black-castor-oil-177ml-usa",
      "ceylon-extra-virgin-coconut-oil",
      "vatika-naturals-coconut-hair-oil-400ml",
      "tresemme-keratin-smooth-shampoo-700ml",
    ],
  },
  {
    id: "col_winter_glow",
    name: "Winter Hydration & Herbal Care",
    slug: "winter-hydration",
    title: "Winter Glow & Barrier Protection",
    subtitle: "Dr. Alvin Kojic, Nivea soft creams, Vaseline intensive care and herbal soaps",
    editorialHeader: "Seal in natural moisture and protect delicate skin from dryness with gentle, dermatologically tested essentials.",
    heroImage: "https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg",
    productSlugs: [
      "dr-alvin-kojic-acid-soap",
      "kojie-san-soap",
      "vaseline-intensive-care-cocoa-glow-400ml",
      "nivea-soft-moisturizer-cream-200ml",
    ],
  },
];

export const PRODUCTS: ProductItem[] = [
  // ==================== SOOTHING BALMS & PAIN RELIEF ====================
  {
    id: "prod_balm_croc",
    slug: "crocodile-balm-50g-thailand",
    name: "Crocodile Herbal Balm 50g",
    subtitle: "Traditional Thai Herbal Pain Relief & Warming Formula",
    description: "An authentic Thai formulation blended with natural herbs and crocodile oil extracts designed for rapid relief from muscular soreness, sprains, backache, and joint tightness. Delivers a soothing warm penetration that eases stiffness.",
    details: "Net Weight: 50g. Origin: Thailand. Active Ingredients: Crocodile oil extract, Camphor, Menthol, Methyl Salicylate, Herbal Essential Oils.",
    materialsInfo: "100% authentic Thai herbal preparation in a glass apothecary jar.",
    dimensionsInfo: "50g Compact Glass Jar (6cm x 6cm).",
    capacityInfo: "50g / 1.76 oz.",
    careInfo: "Apply gently to affected area 2-3 times daily. For external use only. Store in a cool dry place away from direct sunlight.",
    basePrice: 750,
    compareAtPrice: 850,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "herbal-balms",
    collections: ["pain-relief-thermal"],
    tags: ["balm", "pain-relief", "thailand", "herbal", "bestseller"],
    rating: 4.9,
    reviewCount: 38,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg",
    hoverImage: "https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg",
    images: ["https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg"],
    variants: [
      {
        id: "v_croc_50",
        sku: "TH-CROC-50G",
        title: "Crocodile Balm 50g",
        colorName: "Herbal Green",
        colorHex: "#005A64",
        price: 750,
        compareAtPrice: 850,
        inventory: 45,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/AuXI3nOuJdjMzECowT7hK9yL0sUJWwMQ34iJBzJk.jpg"],
      },
    ],
    reviews: [
      {
        id: "r_1",
        authorName: "Rafiqul Islam",
        rating: 5,
        title: "Incredible relief for knee pain",
        body: "Bought this after suffering from knee stiffness. Applied it at night and felt dramatic improvement by morning.",
        createdAt: "2026-09-12",
        verified: true,
      },
    ],
  },
  {
    id: "prod_balm_tiger",
    slug: "siam-tiger-balm-50g",
    name: "Siam Tiger Balm 50g",
    subtitle: "High Potency Muscular Pain Rub - Thailand",
    description: "Classic Siam Tiger Balm formulated with concentrated herbal oils to soothe overworked muscles, tendon strain, insect bites, and tension headaches. Imparts an immediate dual cooling and heating sensation.",
    details: "Net Weight: 50g. Origin: Thailand. Provides targeted fast-absorbing muscular relaxation.",
    materialsInfo: "Pure petroleum base enriched with natural menthol and clove oil.",
    dimensionsInfo: "50g Round Tin/Jar.",
    capacityInfo: "50g.",
    careInfo: "Massage gently into sore joints and muscles.",
    basePrice: 750,
    compareAtPrice: 850,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "herbal-balms",
    collections: ["pain-relief-thermal"],
    tags: ["tiger-balm", "pain-relief", "thailand", "herbal"],
    rating: 4.8,
    reviewCount: 42,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/mkikih87K8gvG9pK0C0i9nHfjoblqhOLkpPpKGcL.jpg",
    hoverImage: "https://valobazar.com/storage/products/mkikih87K8gvG9pK0C0i9nHfjoblqhOLkpPpKGcL.jpg",
    images: ["https://valobazar.com/storage/products/mkikih87K8gvG9pK0C0i9nHfjoblqhOLkpPpKGcL.jpg"],
    variants: [
      {
        id: "v_tiger_50",
        sku: "TH-TIGER-50G",
        title: "Tiger Balm 50g",
        colorName: "Amber Gold",
        colorHex: "#FF6857",
        price: 750,
        compareAtPrice: 850,
        inventory: 60,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/mkikih87K8gvG9pK0C0i9nHfjoblqhOLkpPpKGcL.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_lemongrass",
    slug: "green-seven-lemongrass-balm-50g",
    name: "Green Seven Lemongrass Herbal Balm 50g",
    subtitle: "Refreshing Botanical Aroma & Joint Soother",
    description: "Distilled with pure Thai lemongrass essence (Cymbopogon), Green Seven Balm relieves body tension, repels mosquitoes, and clears nasal passages with an invigorating, uplifting citrus aroma.",
    details: "Net Weight: 50g. Made in Thailand. Refreshing, non-greasy aromatic texture.",
    materialsInfo: "Lemongrass extract, Wintergreen oil, Mint leaves, Pure Beeswax.",
    dimensionsInfo: "50g Standard Jar.",
    capacityInfo: "50g.",
    careInfo: "Inhale vapors for respiratory comfort or rub gently on temples and neck.",
    basePrice: 750,
    compareAtPrice: 800,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "herbal-balms",
    collections: ["pain-relief-thermal"],
    tags: ["lemongrass", "thai-balm", "aromatherapy", "joint-relief"],
    rating: 4.9,
    reviewCount: 29,
    isBestseller: false,
    isNewRelease: true,
    primaryImage: "https://valobazar.com/storage/products/Sn6oU2zq0KGeua60ZX5rUGD7DPviViYKns75ZAb3.jpg",
    hoverImage: "https://valobazar.com/storage/products/Sn6oU2zq0KGeua60ZX5rUGD7DPviViYKns75ZAb3.jpg",
    images: ["https://valobazar.com/storage/products/Sn6oU2zq0KGeua60ZX5rUGD7DPviViYKns75ZAb3.jpg"],
    variants: [
      {
        id: "v_lemon_50",
        sku: "TH-LEMON-50G",
        title: "Lemongrass Balm 50g",
        colorName: "Botanical Green",
        colorHex: "#10B981",
        price: 750,
        compareAtPrice: 800,
        inventory: 35,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/Sn6oU2zq0KGeua60ZX5rUGD7DPviViYKns75ZAb3.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_combo",
    slug: "thai-herbal-balm-combo-3pack",
    name: "Thai Herbal Balm Trio Set",
    subtitle: "Crocodile + Tiger + Lemongrass 3-in-1 Value Pack",
    description: "The ultimate natural wellness collection from Thailand. Includes full 50g jars of Crocodile warming balm, Siam Tiger deep muscle balm, and Green Seven Lemongrass aromatic balm. Save over à§³500 with this complete care bundle.",
    details: "Contains 3 x 50g jars. Ideal for family medicine cabinets, sports bags, and daily care.",
    materialsInfo: "Pure authentic Thai herbal remedies in heavy glass jars.",
    dimensionsInfo: "3-Piece Boxed Set.",
    capacityInfo: "150g Total.",
    careInfo: "Use Crocodile for joints, Tiger for back/neck, and Lemongrass for headaches/stress.",
    basePrice: 1750,
    compareAtPrice: 2250,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "herbal-balms",
    collections: ["pain-relief-thermal"],
    tags: ["combo", "value-pack", "thai-balm", "family-pack", "bestseller"],
    rating: 5.0,
    reviewCount: 54,
    isBestseller: true,
    isFeatured: true,
    isBundle: true,
    primaryImage: "https://valobazar.com/storage/products/3ItSe2xMumQrnmEl6nndtHfd7WBrwCgSUdz8ZdBf.jpg",
    hoverImage: "https://valobazar.com/storage/products/3ItSe2xMumQrnmEl6nndtHfd7WBrwCgSUdz8ZdBf.jpg",
    images: ["https://valobazar.com/storage/products/3ItSe2xMumQrnmEl6nndtHfd7WBrwCgSUdz8ZdBf.jpg"],
    variants: [
      {
        id: "v_combo_3",
        sku: "TH-BALM-TRIO",
        title: "3-Pack Herbal Set",
        colorName: "Assorted Trio",
        colorHex: "#005A64",
        price: 1750,
        compareAtPrice: 2250,
        inventory: 25,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/3ItSe2xMumQrnmEl6nndtHfd7WBrwCgSUdz8ZdBf.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_axe",
    slug: "axe-brand-universal-oil-56ml",
    name: "Axe Brand Universal Oil 56ml",
    subtitle: "Singapore Medicated Oil for Headaches & Dizziness",
    description: "Famous throughout Asia for decades, Axe Brand Universal Oil is handy for soothing headaches, motion sickness, nasal congestion, and insect bites. A clear, non-staining oil with a refreshing herbal eucalyptus menthol fragrance.",
    details: "Volume: 56ml. Origin: Singapore. Licensed medicated formula.",
    materialsInfo: "Menthol crystals, Eucalyptus oil, Camphor, Essential aromatics.",
    dimensionsInfo: "56ml Classic Octagonal Glass Bottle.",
    capacityInfo: "56ml / 1.9 fl oz.",
    careInfo: "Apply a few drops to temples, under nose, or on sore muscles.",
    basePrice: 900,
    compareAtPrice: 1100,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "liniments",
    collections: ["pain-relief-thermal"],
    tags: ["axe-oil", "singapore", "medicated-oil", "headache"],
    rating: 4.9,
    reviewCount: 31,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/2YRgn4xTsA8jXA9ymwORVq4BU57HrPogfYXIcFxJ.jpg",
    hoverImage: "https://valobazar.com/storage/products/2YRgn4xTsA8jXA9ymwORVq4BU57HrPogfYXIcFxJ.jpg",
    images: ["https://valobazar.com/storage/products/2YRgn4xTsA8jXA9ymwORVq4BU57HrPogfYXIcFxJ.jpg"],
    variants: [
      {
        id: "v_axe_56",
        sku: "SG-AXE-56ML",
        title: "Axe Universal Oil 56ml",
        colorName: "Clear Glass",
        colorHex: "#64748B",
        price: 900,
        compareAtPrice: 1100,
        inventory: 40,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/2YRgn4xTsA8jXA9ymwORVq4BU57HrPogfYXIcFxJ.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_omega",
    slug: "omega-pain-killer-liniment-60ml",
    name: "Omega Pain Killer Liniment Oil 60ml",
    subtitle: "Fast Penetrating Deep Heat Liniment - Philippines",
    description: "The trusted Philippine liniment for athletes, seniors, and active individuals. Penetrates deep into aching muscles to relieve rheumatism, sciatica, arthritis, and stiffness with sustained heat therapy.",
    details: "Volume: 60ml. Made in Philippines. Quick-absorbing topical formula.",
    materialsInfo: "Methyl Salicylate, Menthol, Camphor, Turpentine Oil.",
    dimensionsInfo: "60ml Bottle.",
    capacityInfo: "60ml.",
    careInfo: "Rub thoroughly until skin feels comfortably warm.",
    basePrice: 870,
    compareAtPrice: 980,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "liniments",
    collections: ["pain-relief-thermal"],
    tags: ["liniment", "omega-oil", "philippines", "deep-heat"],
    rating: 4.8,
    reviewCount: 19,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/I4K0UUH5g8wFqiXLxuoSDDuwXQpTWNsiaxicsT9c.jpg",
    hoverImage: "https://valobazar.com/storage/products/I4K0UUH5g8wFqiXLxuoSDDuwXQpTWNsiaxicsT9c.jpg",
    images: ["https://valobazar.com/storage/products/I4K0UUH5g8wFqiXLxuoSDDuwXQpTWNsiaxicsT9c.jpg"],
    variants: [
      {
        id: "v_omega_60",
        sku: "PH-OMEGA-60ML",
        title: "Omega Liniment 60ml",
        colorName: "Amber Oil",
        colorHex: "#EA580C",
        price: 870,
        compareAtPrice: 980,
        inventory: 30,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/I4K0UUH5g8wFqiXLxuoSDDuwXQpTWNsiaxicsT9c.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_hongthai",
    slug: "hong-thai-herbal-inhaler-thailand",
    name: "Hong Thai Traditional Herbal Inhaler",
    subtitle: "Famous Thai Herbal Inhaler Jar - 100% Natural Botanicals",
    description: "The viral Thai herbal inhaler crafted with fermented herbs, clove, eucalyptus, and menthol. Clears blocked sinuses, cures faintness, improves focus, and calms anxiety instantly with a deeply refreshing herbal draft.",
    details: "Weight: 40g. Imported from Bangkok, Thailand. Contains pure dry herbs inside protective mesh.",
    materialsInfo: "Dried herbal botanical mix, camphor, borneol, peppermint.",
    dimensionsInfo: "Pocket Sized Inhaler Jar (Green Pot).",
    capacityInfo: "40g.",
    careInfo: "Twist cap open and inhale deeply through both nostrils. Keep tightly capped after use.",
    basePrice: 450,
    compareAtPrice: 550,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "inhalers",
    collections: ["pain-relief-thermal"],
    tags: ["hong-thai", "inhaler", "thai-herb", "sinus-relief", "bestseller"],
    rating: 5.0,
    reviewCount: 88,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/2d7nUIPN8MdLxK9OsUmJAikfYm8SoqIEh7M4o1EP.webp",
    hoverImage: "https://valobazar.com/storage/products/2d7nUIPN8MdLxK9OsUmJAikfYm8SoqIEh7M4o1EP.webp",
    images: ["https://valobazar.com/storage/products/2d7nUIPN8MdLxK9OsUmJAikfYm8SoqIEh7M4o1EP.webp"],
    variants: [
      {
        id: "v_hong_thai",
        sku: "TH-HONGTHAI-POT",
        title: "Hong Thai Inhaler Pot",
        colorName: "Original Green",
        colorHex: "#15803D",
        price: 450,
        compareAtPrice: 550,
        inventory: 90,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/2d7nUIPN8MdLxK9OsUmJAikfYm8SoqIEh7M4o1EP.webp"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_pimsaen8",
    slug: "pim-saen-balm-oil-8ml-poysian",
    name: "Pim-Saen Balm Oil 8ml (Poy-Sian Thai)",
    subtitle: "Borneol Herbal Inhaler & Roll-on - Bangkok",
    description: "Compact 8ml Pim-Saen herbal balm oil from Poy-Sian. Features pure Borneol (Pim Saen) crystals dissolved in soothing oils for rapid relief from dizziness, nausea, headaches, and bug bites on the move.",
    details: "Volume: 8ml. Made in Thailand. Roll-on or dab applicator.",
    materialsInfo: "Borneol, Menthol, Camphor, Eucalyptus.",
    dimensionsInfo: "Pocket Roller Bottle 8ml.",
    capacityInfo: "8ml.",
    careInfo: "Roll lightly on temples or inhale from opening.",
    basePrice: 150,
    compareAtPrice: 200,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "inhalers",
    collections: ["pain-relief-thermal"],
    tags: ["poy-sian", "roll-on", "pocket-balm", "headache"],
    rating: 4.8,
    reviewCount: 35,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/tHVmovSEK8pkLnGSSPedIB9gBhXRy2NH9RAZPmp9.jpg",
    hoverImage: "https://valobazar.com/storage/products/tHVmovSEK8pkLnGSSPedIB9gBhXRy2NH9RAZPmp9.jpg",
    images: ["https://valobazar.com/storage/products/tHVmovSEK8pkLnGSSPedIB9gBhXRy2NH9RAZPmp9.jpg"],
    variants: [
      {
        id: "v_pim_8",
        sku: "TH-PIM-8ML",
        title: "Pim-Saen 8ml",
        colorName: "Clear Glass Roller",
        colorHex: "#0284C7",
        price: 150,
        compareAtPrice: 200,
        inventory: 75,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/tHVmovSEK8pkLnGSSPedIB9gBhXRy2NH9RAZPmp9.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_pimsaen5",
    slug: "pim-saen-balm-oil-rollon-5ml",
    name: "Pim Saen Balm Oil Roll-On 5ml",
    subtitle: "Concentrated Herbal Roller for Temples & Pulse Points",
    description: "Ultra-portable roller bottle infused with cooling essential oils and borneol camphor. Perfectly calibrated for soothing tension headaches during work hours and transit.",
    details: "Volume: 5ml. High potency Thai borneol roll-on.",
    materialsInfo: "Concentrated borneol oil blend.",
    dimensionsInfo: "5ml Miniature Roll-on.",
    capacityInfo: "5ml.",
    careInfo: "Apply directly to temples, wrists, and back of neck.",
    basePrice: 250,
    compareAtPrice: 320,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "inhalers",
    collections: ["pain-relief-thermal"],
    tags: ["roll-on", "pim-saen", "thai-balm"],
    rating: 4.7,
    reviewCount: 16,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/mhMs0p3j2YCAMMWbuzAvu8DR5p4U4Jg9AK9zoLzq.jpg",
    hoverImage: "https://valobazar.com/storage/products/mhMs0p3j2YCAMMWbuzAvu8DR5p4U4Jg9AK9zoLzq.jpg",
    images: ["https://valobazar.com/storage/products/mhMs0p3j2YCAMMWbuzAvu8DR5p4U4Jg9AK9zoLzq.jpg"],
    variants: [
      {
        id: "v_pim_5",
        sku: "TH-PIM-5ML",
        title: "Pim Saen 5ml",
        colorName: "5ml Glass",
        colorHex: "#0D9488",
        price: 250,
        compareAtPrice: 320,
        inventory: 50,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/mhMs0p3j2YCAMMWbuzAvu8DR5p4U4Jg9AK9zoLzq.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_balm_vicks",
    slug: "vicks-vaporub-100g",
    name: "Vicks VapoRub 100g",
    subtitle: "Cough & Cold Vaporizing Ointment",
    description: "The gold standard vaporizing ointment for cough, chest congestion, and minor muscle aches. Inhaling medicated vapors provides up to 8 hours of comforting relief from cold symptoms.",
    details: "Net Weight: 100g. Proven medicated steam formula.",
    materialsInfo: "Camphor, Menthol, Eucalyptus Oil in petroleum base.",
    dimensionsInfo: "100g Blue Tub.",
    capacityInfo: "100g.",
    careInfo: "Rub thick layer on chest and throat. Can also be added to hot water for steam inhalation.",
    basePrice: 950,
    compareAtPrice: 1100,
    currency: "BDT",
    categorySlug: "soothing-balms",
    categoryName: "Soothing Balms & Pain Relief",
    subcategorySlug: "herbal-balms",
    collections: ["pain-relief-thermal"],
    tags: ["vicks", "vaporub", "cold-relief", "cough"],
    rating: 4.9,
    reviewCount: 45,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/IvSMGvwDl1qEWdrnoC8ro7zufibMMgHMzdLnhy4k.jpg",
    hoverImage: "https://valobazar.com/storage/products/IvSMGvwDl1qEWdrnoC8ro7zufibMMgHMzdLnhy4k.jpg",
    images: ["https://valobazar.com/storage/products/IvSMGvwDl1qEWdrnoC8ro7zufibMMgHMzdLnhy4k.jpg"],
    variants: [
      {
        id: "v_vicks_100",
        sku: "VCK-100G",
        title: "Vicks VapoRub 100g",
        colorName: "Cobalt Blue Tub",
        colorHex: "#1E40AF",
        price: 950,
        compareAtPrice: 1100,
        inventory: 55,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/IvSMGvwDl1qEWdrnoC8ro7zufibMMgHMzdLnhy4k.jpg"],
      },
    ],
    reviews: [],
  },

  // ==================== HAIR OILS & SCALP CARE ====================
  {
    id: "prod_hair_jamaican",
    slug: "jamaican-black-castor-oil-177ml-usa",
    name: "Jamaican Black Castor Oil 177.4ml (USA)",
    subtitle: "100% Pure Extra Dark Castor Oil for Hair Growth",
    description: "Authentic roasted castor bean oil from Jamaica, bottled in the USA. Rich in ricinoleic acid and essential minerals that stimulate dormant hair follicles, thicken thinning edges, and eliminate scalp dandruff.",
    details: "Volume: 177.4ml (6 fl oz). Unrefined extra dark cold-pressed formula. Sulfate and paraben free.",
    materialsInfo: "100% Pure Ricinus Communis (Castor) Seed Oil with natural ash.",
    dimensionsInfo: "177.4ml Bottle.",
    capacityInfo: "177.4ml / 6 oz.",
    careInfo: "Warm a few drops in palms and massage into scalp 2-3 times per week. Can be left overnight.",
    basePrice: 2000,
    compareAtPrice: 2400,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "castor-oils",
    collections: ["hair-growth-scalp"],
    tags: ["castor-oil", "jamaican", "hair-growth", "scalp-treatment", "bestseller"],
    rating: 5.0,
    reviewCount: 67,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg",
    hoverImage: "https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg",
    images: ["https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg"],
    variants: [
      {
        id: "v_jbco_177",
        sku: "USA-JBCO-177ML",
        title: "Jamaican Castor Oil 177ml",
        colorName: "Deep Amber Glass",
        colorHex: "#78350F",
        price: 2000,
        compareAtPrice: 2400,
        inventory: 40,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/a8oLSJS01bzqqhs49M96cwCqrLorPfxEDw9bfdw9.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_hair_ceylon",
    slug: "ceylon-extra-virgin-coconut-oil",
    name: "Ceylon Organic Extra Virgin Coconut Oil",
    subtitle: "Cold-Pressed Virgin Scalp & Hair Nutrition",
    description: "Extracted from fresh handpicked Sri Lankan coconuts through cold centrifugation without chemical heat. Restores dry brittle hair strands, hydrates the scalp, and leaves a silky, lustrous sheen.",
    details: "Net Volume: 250ml. 100% Raw Extra Virgin Cold-Pressed.",
    materialsInfo: "Cold-pressed Cocos Nucifera (Coconut) Oil.",
    dimensionsInfo: "250ml Glass Jar.",
    capacityInfo: "250ml.",
    careInfo: "Apply as pre-shampoo hair treatment or daily cuticle seal.",
    basePrice: 520,
    compareAtPrice: 650,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "coconut-oils",
    collections: ["hair-growth-scalp"],
    tags: ["coconut-oil", "ceylon", "organic", "extra-virgin"],
    rating: 4.8,
    reviewCount: 28,
    isBestseller: false,
    isNewRelease: true,
    primaryImage: "https://valobazar.com/storage/products/sOKscKOQ52xIeLOA5ecrNI9ZxW9uzbhGUXTIZBwG.jpg",
    hoverImage: "https://valobazar.com/storage/products/sOKscKOQ52xIeLOA5ecrNI9ZxW9uzbhGUXTIZBwG.jpg",
    images: ["https://valobazar.com/storage/products/sOKscKOQ52xIeLOA5ecrNI9ZxW9uzbhGUXTIZBwG.jpg"],
    variants: [
      {
        id: "v_ceylon_coco",
        sku: "CEY-COCO-250ML",
        title: "Ceylon Virgin Coconut 250ml",
        colorName: "Pure White / Clear",
        colorHex: "#F8FAFC",
        price: 520,
        compareAtPrice: 650,
        inventory: 50,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/sOKscKOQ52xIeLOA5ecrNI9ZxW9uzbhGUXTIZBwG.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_hair_vatika",
    slug: "vatika-naturals-coconut-hair-oil-400ml",
    name: "Vatika Naturals Enriched Coconut Hair Oil 400ml",
    subtitle: "Enriched with Henna, Amla, Lemon & Ayurvedic Herbs",
    description: "Tri-active formula infusing pure coconut oil with Henna (for hair color and strength), Amla (for follicle nourishment), and Lemon (for anti-dandruff control).",
    details: "Volume: 400ml. Ayurvedic enriched formula for healthy voluminous hair.",
    materialsInfo: "Coconut oil, Amla extract, Henna extract, Lemon oil.",
    dimensionsInfo: "400ml Squeeze Bottle.",
    capacityInfo: "400ml.",
    careInfo: "Massage into scalp and hair length prior to bath.",
    basePrice: 950,
    compareAtPrice: 1150,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "coconut-oils",
    collections: ["hair-growth-scalp"],
    tags: ["vatika", "coconut-oil", "herbal", "amla"],
    rating: 4.8,
    reviewCount: 33,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/cGyg3PcYjqkGpqtkDUOpHTWwK101TzNzbMhJRObd.jpg",
    hoverImage: "https://valobazar.com/storage/products/cGyg3PcYjqkGpqtkDUOpHTWwK101TzNzbMhJRObd.jpg",
    images: ["https://valobazar.com/storage/products/cGyg3PcYjqkGpqtkDUOpHTWwK101TzNzbMhJRObd.jpg"],
    variants: [
      {
        id: "v_vatika_400",
        sku: "VAT-COCO-400ML",
        title: "Vatika Hair Oil 400ml",
        colorName: "Emerald Green Bottle",
        colorHex: "#047857",
        price: 950,
        compareAtPrice: 1150,
        inventory: 45,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/cGyg3PcYjqkGpqtkDUOpHTWwK101TzNzbMhJRObd.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_hair_parachute",
    slug: "parachute-sampoorna-coconut-oil-300ml",
    name: "Parachute Sampoorna Coconut Hair Oil 300ml",
    subtitle: "Enriched with Methi & Hibiscus Botanical Extracts",
    description: "Formulated with pure coconut oil enriched with Methi (fenugreek) and Hibiscus flowers to stop excessive hair fall, condition dry tips, and promote root density.",
    details: "Volume: 300ml. Authentic Parachute herbal formulation.",
    materialsInfo: "Pure coconut oil, Methi, Hibiscus extracts.",
    dimensionsInfo: "300ml Bottle.",
    capacityInfo: "300ml.",
    careInfo: "Use daily or 3 times a week for maximum hair density.",
    basePrice: 600,
    compareAtPrice: 750,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "coconut-oils",
    collections: ["hair-growth-scalp"],
    tags: ["parachute", "coconut-oil", "sampoorna", "anti-hairfall"],
    rating: 4.7,
    reviewCount: 22,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/QON9YebgMWQgLwia3NO1TOXVtjmZDdpf5pgKQavD.jpg",
    hoverImage: "https://valobazar.com/storage/products/QON9YebgMWQgLwia3NO1TOXVtjmZDdpf5pgKQavD.jpg",
    images: ["https://valobazar.com/storage/products/QON9YebgMWQgLwia3NO1TOXVtjmZDdpf5pgKQavD.jpg"],
    variants: [
      {
        id: "v_para_300",
        sku: "PAR-SAMP-300ML",
        title: "Parachute 300ml",
        colorName: "Deep Blue Bottle",
        colorHex: "#1E3A8A",
        price: 600,
        compareAtPrice: 750,
        inventory: 60,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/QON9YebgMWQgLwia3NO1TOXVtjmZDdpf5pgKQavD.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_hair_tresemme_shampoo",
    slug: "tresemme-keratin-smooth-shampoo-700ml",
    name: "TRESemme Keratin Smooth Shampoo 700ml",
    subtitle: "Salon Quality Anti-Frizz & Marula Oil Nourishment",
    description: "Professional salon-formula shampoo infused with hydrolyzed keratin and luxurious African marula oil. Controls frizz for up to 72 hours while leaving hair silky, manageable, and shiny.",
    details: "Volume: 700ml Big Pump Bottle. Suitable for color-treated and chemically styled hair.",
    materialsInfo: "Hydrolyzed Keratin, Marula Oil, Gentle Cleansing Surfactants.",
    dimensionsInfo: "700ml Salon Pump Dispenser.",
    capacityInfo: "700ml.",
    careInfo: "Apply to wet hair, lather gently from scalp to ends, and rinse thoroughly.",
    basePrice: 1450,
    compareAtPrice: 1700,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "shampoos",
    collections: ["hair-growth-scalp"],
    tags: ["tresemme", "keratin", "shampoo", "anti-frizz", "bestseller"],
    rating: 4.9,
    reviewCount: 51,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/yFet95AMfxX7PbQtvtWRaGiwH7b7OP0WnaJPXALG.jpg",
    hoverImage: "https://valobazar.com/storage/products/yFet95AMfxX7PbQtvtWRaGiwH7b7OP0WnaJPXALG.jpg",
    images: ["https://valobazar.com/storage/products/yFet95AMfxX7PbQtvtWRaGiwH7b7OP0WnaJPXALG.jpg"],
    variants: [
      {
        id: "v_tresemme_700",
        sku: "TRE-KERA-700ML",
        title: "TRESemme Keratin 700ml",
        colorName: "Ruby Red Bottle",
        colorHex: "#991B1B",
        price: 1450,
        compareAtPrice: 1700,
        inventory: 35,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/yFet95AMfxX7PbQtvtWRaGiwH7b7OP0WnaJPXALG.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_hair_herbal_coconut",
    slug: "herbal-essences-hydrate-coconut-milk-600ml",
    name: "Herbal Essences Hydrate Coconut Milk Shampoo 600ml",
    subtitle: "Real Botanical Bio:Renew Hydrating Cleanser - Thailand",
    description: "Formulated with 90% natural origin ingredients including real antioxidant-rich coconut milk extracts and aloe. Replenishes dry moisture-starved hair with a heavenly tropical scent.",
    details: "Volume: 600ml. Certified botanical extracts by the Royal Botanic Gardens, Kew.",
    materialsInfo: "Coconut milk extract, Aloe vera, Sea kelp, 0% Parabens, Colorants.",
    dimensionsInfo: "600ml Bottle.",
    capacityInfo: "600ml.",
    careInfo: "Lather into wet hair and rinse.",
    basePrice: 1700,
    compareAtPrice: 2000,
    currency: "BDT",
    categorySlug: "hair-oils",
    categoryName: "Hair Oils & Scalp Care",
    subcategorySlug: "shampoos",
    collections: ["hair-growth-scalp"],
    tags: ["herbal-essences", "coconut-milk", "shampoo", "thailand"],
    rating: 4.8,
    reviewCount: 30,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/qpcrilkHwLdoxu967IkubBzAGZiUbouQwYfr1l0P.jpg",
    hoverImage: "https://valobazar.com/storage/products/qpcrilkHwLdoxu967IkubBzAGZiUbouQwYfr1l0P.jpg",
    images: ["https://valobazar.com/storage/products/qpcrilkHwLdoxu967IkubBzAGZiUbouQwYfr1l0P.jpg"],
    variants: [
      {
        id: "v_herb_coco_600",
        sku: "HE-COCO-600ML",
        title: "Coconut Milk 600ml",
        colorName: "Teal Bottle",
        colorHex: "#0D9488",
        price: 1700,
        compareAtPrice: 2000,
        inventory: 28,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/qpcrilkHwLdoxu967IkubBzAGZiUbouQwYfr1l0P.jpg"],
      },
    ],
    reviews: [],
  },

  // ==================== ESSENTIAL OILS & PURE WELLNESS ====================
  {
    id: "prod_oil_royal",
    slug: "royal-extra-virgin-olive-oil-4l",
    name: "Royal Extra Virgin Olive Oil 4L (Spain)",
    subtitle: "First Cold-Pressed Spanish Extra Virgin Olive Oil Tin",
    description: "Imported directly from Spanish olive orchards in Andalusia. First cold-pressed with acidity strictly under 0.5%. Perfect for healthy Mediterranean salads, therapeutic cooking, and pure skincare/hair moisture baths.",
    details: "Volume: 4 Liters Tin Can. Origin: Spain. First Cold Pressed Extra Virgin.",
    materialsInfo: "100% Pure Extra Virgin Olive Oil (Olea Europaea).",
    dimensionsInfo: "4L Metal Culinary Storage Tin.",
    capacityInfo: "4000ml / 4 Liters.",
    careInfo: "Store in cool dry conditions away from heat and light.",
    basePrice: 4450,
    compareAtPrice: 4950,
    currency: "BDT",
    categorySlug: "essential-oils",
    categoryName: "Essential Oils & Pure Wellness",
    subcategorySlug: "olive-oils",
    collections: [],
    tags: ["olive-oil", "spain", "extra-virgin", "royal", "bestseller"],
    rating: 5.0,
    reviewCount: 47,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/pK1LvLffIYWkiaqjmWQ5HotveXgBGWnH0c1JrOsU.jpg",
    hoverImage: "https://valobazar.com/storage/products/pK1LvLffIYWkiaqjmWQ5HotveXgBGWnH0c1JrOsU.jpg",
    images: ["https://valobazar.com/storage/products/pK1LvLffIYWkiaqjmWQ5HotveXgBGWnH0c1JrOsU.jpg"],
    variants: [
      {
        id: "v_royal_4l",
        sku: "SPN-ROYAL-4L",
        title: "Royal EVOO 4L Tin",
        colorName: "Gold Tin",
        colorHex: "#CA8A04",
        price: 4450,
        compareAtPrice: 4950,
        inventory: 30,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/pK1LvLffIYWkiaqjmWQ5HotveXgBGWnH0c1JrOsU.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_oil_span_oliva",
    slug: "span-oliva-extra-virgin-olive-oil-1l",
    name: "Span Oliva Extra Virgin Olive Oil 1L (Spain)",
    subtitle: "Glass Bottle Premium Spanish Olive Oil",
    description: "Single-origin Spanish olive oil bottled in dark protective glass to preserve delicate polyphenols and antioxidants. Features a fruity, balanced olive profile ideal for both table salad dressing and hair therapy.",
    details: "Volume: 1000ml (1L). Dark Glass Bottle. Product of Spain.",
    materialsInfo: "100% Spanish Extra Virgin Olive Oil.",
    dimensionsInfo: "1 Liter Bottle.",
    capacityInfo: "1000ml.",
    careInfo: "Keep capped tightly in pantry cupboard.",
    basePrice: 1250,
    compareAtPrice: 1500,
    currency: "BDT",
    categorySlug: "essential-oils",
    categoryName: "Essential Oils & Pure Wellness",
    subcategorySlug: "olive-oils",
    collections: [],
    tags: ["olive-oil", "spain", "span-oliva", "extra-virgin"],
    rating: 4.8,
    reviewCount: 23,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/uqnG9X0izqR1b5nkyUHzbfkf1x4RqBlyxeIlRGoj.jpg",
    hoverImage: "https://valobazar.com/storage/products/uqnG9X0izqR1b5nkyUHzbfkf1x4RqBlyxeIlRGoj.jpg",
    images: ["https://valobazar.com/storage/products/uqnG9X0izqR1b5nkyUHzbfkf1x4RqBlyxeIlRGoj.jpg"],
    variants: [
      {
        id: "v_span_1l",
        sku: "SPN-OLIVA-1L",
        title: "Span Oliva 1L Bottle",
        colorName: "Dark Green Glass",
        colorHex: "#14532D",
        price: 1250,
        compareAtPrice: 1500,
        inventory: 45,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/uqnG9X0izqR1b5nkyUHzbfkf1x4RqBlyxeIlRGoj.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_oil_evoo_spain4l",
    slug: "extra-virgin-olive-oil-coldpress-4l-spain",
    name: "Spanish First Cold-Pressed Extra Virgin Olive Oil 4L",
    subtitle: "Commercial Grade Gourmet EVOO Tin - Spain",
    description: "Premium large tin of unfiltered, cold-pressed culinary and wellness olive oil. Harvested from mature Spanish olive trees for robust aroma and highest grade nutrition.",
    details: "Volume: 4 Liters Tin. High smoke point cold extraction.",
    materialsInfo: "Pure Cold-Pressed Virgin Olive Oil.",
    dimensionsInfo: "4L Metallic Can.",
    capacityInfo: "4000ml.",
    careInfo: "Store at ambient room temperature.",
    basePrice: 5200,
    compareAtPrice: 5800,
    currency: "BDT",
    categorySlug: "essential-oils",
    categoryName: "Essential Oils & Pure Wellness",
    subcategorySlug: "olive-oils",
    collections: [],
    tags: ["evoo", "olive-oil", "spain", "premium"],
    rating: 4.9,
    reviewCount: 18,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/IPtpJty2TlYmwuE0zKImon5ALBWLFl5Y2Dp2Psde.jpg",
    hoverImage: "https://valobazar.com/storage/products/IPtpJty2TlYmwuE0zKImon5ALBWLFl5Y2Dp2Psde.jpg",
    images: ["https://valobazar.com/storage/products/IPtpJty2TlYmwuE0zKImon5ALBWLFl5Y2Dp2Psde.jpg"],
    variants: [
      {
        id: "v_evoo_spn_4l",
        sku: "SPN-EVOO-CAN4L",
        title: "Spanish 4L Gourmet Tin",
        colorName: "Classic Olive Tin",
        colorHex: "#3F6212",
        price: 5200,
        compareAtPrice: 5800,
        inventory: 20,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/IPtpJty2TlYmwuE0zKImon5ALBWLFl5Y2Dp2Psde.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_oil_bonlife_sunflower",
    slug: "bonlife-sunflower-seed-oil-5000ml",
    name: "Bonlife 100% Pure Sunflower Seed Oil 5L",
    subtitle: "Cholesterol-Free & Trans-Fat Free Heart Care Oil",
    description: "Healthy, light, and cholesterol-free cooking oil pressed from golden sunflower seeds. Packed with natural Vitamin E for cardiovascular wellness and skin health.",
    details: "Volume: 5000ml (5 Liters Can). Zero trans-fats. Certified high-grade seed oil.",
    materialsInfo: "100% Refined Sunflower Seed Oil.",
    dimensionsInfo: "5L Can with Sturdy Handle.",
    capacityInfo: "5000ml.",
    careInfo: "Ideal for daily high-heat culinary recipes.",
    basePrice: 2200,
    compareAtPrice: 2500,
    currency: "BDT",
    categorySlug: "essential-oils",
    categoryName: "Essential Oils & Pure Wellness",
    subcategorySlug: "seed-oils",
    collections: [],
    tags: ["sunflower-oil", "bonlife", "heart-healthy", "cholesterol-free"],
    rating: 4.8,
    reviewCount: 39,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/UnAXX06WdYQpsUe1nKg6ubTMqt9KG6jVT7AivnGr.jpg",
    hoverImage: "https://valobazar.com/storage/products/UnAXX06WdYQpsUe1nKg6ubTMqt9KG6jVT7AivnGr.jpg",
    images: ["https://valobazar.com/storage/products/UnAXX06WdYQpsUe1nKg6ubTMqt9KG6jVT7AivnGr.jpg"],
    variants: [
      {
        id: "v_bonlife_5l",
        sku: "BON-SUN-5L",
        title: "Bonlife 5L Can",
        colorName: "Golden Yellow",
        colorHex: "#EAB308",
        price: 2200,
        compareAtPrice: 2500,
        inventory: 40,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/UnAXX06WdYQpsUe1nKg6ubTMqt9KG6jVT7AivnGr.jpg"],
      },
    ],
    reviews: [],
  },

  // ==================== HERBAL & WINTER SKIN CARE ====================
  {
    id: "prod_skin_dralvin",
    slug: "dr-alvin-kojic-acid-soap",
    name: "Dr. Alvin Original Kojic Acid Soap",
    subtitle: "Dermatologist Tested Skin Brightening Soap - Philippines",
    description: "The famed whitening and acne-clearing soap formulated by Dr. Alvin. Formulated with authentic Kojic Acid to gently exfoliate dead skin layers, fade hyperpigmentation, dark acne spots, and brighten dull skin tone.",
    details: "Net Weight: 135g. Made in Philippines. Clinically proven dermatologist formula.",
    materialsInfo: "Kojic Acid, Virgin Coconut Oil, Glycerin, Orange Peel Extract.",
    dimensionsInfo: "135g Bar Soap.",
    capacityInfo: "135g.",
    careInfo: "Lather with water, gently apply to face and neck for 30 seconds, then rinse with cool water.",
    basePrice: 700,
    compareAtPrice: 850,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "cleansers",
    collections: ["winter-hydration"],
    tags: ["dr-alvin", "kojic-soap", "philippines", "whitening", "bestseller"],
    rating: 4.9,
    reviewCount: 92,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg",
    hoverImage: "https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg",
    images: ["https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg"],
    variants: [
      {
        id: "v_alvin_135",
        sku: "PH-ALVIN-135G",
        title: "Dr. Alvin Kojic Bar",
        colorName: "Vibrant Orange",
        colorHex: "#F97316",
        price: 700,
        compareAtPrice: 850,
        inventory: 80,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/AiogpNfDBLHrfbtAIhneEOPJd5UGyw2UIRmbJYqX.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_kojiesan",
    slug: "kojie-san-soap",
    name: "Kojie San Skin Lightening Soap 65g/135g",
    subtitle: "High Grade Japanese Kojic Acid with Zero Pigment Light",
    description: "The global cult-favorite Kojic soap. Blends natural high-grade Kojic acid with nourishing coconut oil to reduce melanin spots, age spots, and uneven sun tans for visibly lighter and glowing skin.",
    details: "Net Weight: 135g. Original Kojie San hologram seal on packaging.",
    materialsInfo: "Pure Kojic Acid, Cocos Nucifera Oil, Tea Tree Oil, Vitamin C.",
    dimensionsInfo: "135g Bar Soap.",
    capacityInfo: "135g.",
    careInfo: "Use twice daily. Follow with a hydrating moisturizer and sunscreen.",
    basePrice: 550,
    compareAtPrice: 680,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "cleansers",
    collections: ["winter-hydration"],
    tags: ["kojie-san", "soap", "skin-lightening", "pigmentation"],
    rating: 4.8,
    reviewCount: 74,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/T74cgm4ro3zypkmguXLRAo6koNyypU1STB0uyIZD.jpg",
    hoverImage: "https://valobazar.com/storage/products/T74cgm4ro3zypkmguXLRAo6koNyypU1STB0uyIZD.jpg",
    images: ["https://valobazar.com/storage/products/T74cgm4ro3zypkmguXLRAo6koNyypU1STB0uyIZD.jpg"],
    variants: [
      {
        id: "v_kojie_135",
        sku: "KOJ-SAN-135G",
        title: "Kojie San 135g",
        colorName: "Sunset Orange",
        colorHex: "#EA580C",
        price: 550,
        compareAtPrice: 680,
        inventory: 65,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/T74cgm4ro3zypkmguXLRAo6koNyypU1STB0uyIZD.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_himalaya_neem",
    slug: "himalaya-purifying-neem-face-wash",
    name: "Himalaya Purifying Neem Face Wash 150ml",
    subtitle: "Soap-Free Herbal Acne & Oil Control Cleanser",
    description: "Ayurvedic formulation blending Neem and Turmeric. Cleanses deep seated impurities, removes excess oil, and prevents stubborn acne breakouts without leaving skin feeling tight or dehydrated.",
    details: "Volume: 150ml Tube. Soap-free, dermatologically tested herbal cleanser.",
    materialsInfo: "Neem (Azadirachta Indica), Turmeric (Curcuma Longa).",
    dimensionsInfo: "150ml Squeeze Tube.",
    capacityInfo: "150ml.",
    careInfo: "Moisten face, apply small quantity and gently work into lather, then rinse.",
    basePrice: 550,
    compareAtPrice: 650,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "cleansers",
    collections: ["winter-hydration"],
    tags: ["himalaya", "neem", "face-wash", "acne-control"],
    rating: 4.8,
    reviewCount: 46,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/uxIpSFYw2mg3Aurmy6eISTarCj1MBjW3ZmyQ5vVd.jpg",
    hoverImage: "https://valobazar.com/storage/products/uxIpSFYw2mg3Aurmy6eISTarCj1MBjW3ZmyQ5vVd.jpg",
    images: ["https://valobazar.com/storage/products/uxIpSFYw2mg3Aurmy6eISTarCj1MBjW3ZmyQ5vVd.jpg"],
    variants: [
      {
        id: "v_him_neem_150",
        sku: "HIM-NEEM-150ML",
        title: "Himalaya Neem 150ml",
        colorName: "Leaf Green",
        colorHex: "#16A34A",
        price: 550,
        compareAtPrice: 650,
        inventory: 50,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/uxIpSFYw2mg3Aurmy6eISTarCj1MBjW3ZmyQ5vVd.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_neutrogena_hydro",
    slug: "neutrogena-hydro-boost-cleanser",
    name: "Neutrogena Hydro Boost Water Gel Cleanser",
    subtitle: "Hyaluronic Acid Hydrating Face Cleanser",
    description: "An innovative, lightweight water-gel cleanser activated with water to remove dirt, makeup, and oil. Features Hyaluronic Acid to lock in hydration and maintain the delicate skin moisture barrier.",
    details: "Volume: 200ml Pump Bottle. Oil-free, non-comedogenic, safe for sensitive skin.",
    materialsInfo: "Hyaluronic acid, Glycerin, Gentle cleansing agents.",
    dimensionsInfo: "200ml Bottle.",
    capacityInfo: "200ml.",
    careInfo: "Apply to wet skin, massage gently, and rinse.",
    basePrice: 1150,
    compareAtPrice: 1350,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "cleansers",
    collections: ["winter-hydration"],
    tags: ["neutrogena", "hydro-boost", "hyaluronic", "cleanser"],
    rating: 4.9,
    reviewCount: 38,
    isBestseller: false,
    isNewRelease: true,
    primaryImage: "https://valobazar.com/storage/products/NDZ5OY40X1R2IVcIpdKuWTlzJ1e22272ahknJ2r8.jpg",
    hoverImage: "https://valobazar.com/storage/products/NDZ5OY40X1R2IVcIpdKuWTlzJ1e22272ahknJ2r8.jpg",
    images: ["https://valobazar.com/storage/products/NDZ5OY40X1R2IVcIpdKuWTlzJ1e22272ahknJ2r8.jpg"],
    variants: [
      {
        id: "v_neutro_200",
        sku: "NEU-HYDRO-200ML",
        title: "Hydro Boost 200ml",
        colorName: "Aqua Blue",
        colorHex: "#0284C7",
        price: 1150,
        compareAtPrice: 1350,
        inventory: 30,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/NDZ5OY40X1R2IVcIpdKuWTlzJ1e22272ahknJ2r8.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_vaseline_cocoa",
    slug: "vaseline-intensive-care-cocoa-glow-400ml",
    name: "Vaseline Intensive Care Cocoa Glow Body Lotion 400ml",
    subtitle: "100% Pure Cocoa & Shea Butter Deep Moisturization",
    description: "Deeply restores dry skin and brings out its natural warm glow. Enriched with 100% pure cocoa and shea butter combined with micro-droplets of Vaseline Jelly to heal dryness beneath the surface.",
    details: "Volume: 400ml Smart Pump Bottle. Fast absorbing, non-greasy lotion.",
    materialsInfo: "Pure Cocoa Butter, Shea Butter, Vaseline Jelly micro-droplets.",
    dimensionsInfo: "400ml Bottle.",
    capacityInfo: "400ml.",
    careInfo: "Massage generously across body daily, particularly post-shower.",
    basePrice: 1000,
    compareAtPrice: 1200,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "lotions",
    collections: ["winter-hydration"],
    tags: ["vaseline", "cocoa-glow", "body-lotion", "winter-care", "bestseller"],
    rating: 4.9,
    reviewCount: 63,
    isBestseller: true,
    isFeatured: true,
    primaryImage: "https://valobazar.com/storage/products/Xr4ThqRME44mZKhF4iHO4Sd4aXLdu93Z6sYJc8jN.jpg",
    hoverImage: "https://valobazar.com/storage/products/Xr4ThqRME44mZKhF4iHO4Sd4aXLdu93Z6sYJc8jN.jpg",
    images: ["https://valobazar.com/storage/products/Xr4ThqRME44mZKhF4iHO4Sd4aXLdu93Z6sYJc8jN.jpg"],
    variants: [
      {
        id: "v_vas_cocoa_400",
        sku: "VAS-COCOA-400ML",
        title: "Cocoa Glow 400ml",
        colorName: "Cocoa Bronze",
        colorHex: "#78350F",
        price: 1000,
        compareAtPrice: 1200,
        inventory: 50,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/Xr4ThqRME44mZKhF4iHO4Sd4aXLdu93Z6sYJc8jN.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_nivea_soft200",
    slug: "nivea-soft-moisturizer-cream-200ml",
    name: "Nivea Soft Refreshingly Soft Moisturizing Cream 200ml",
    subtitle: "Jojoba Oil & Vitamin E All-Purpose Hydration - UAE",
    description: "An invigorating all-purpose moisturizing cream with an ultra-light texture. Absorbs quickly into skin to deliver a refreshing moisture boost to face, body, and hands throughout winter.",
    details: "Net Volume: 200ml Tub. Made in UAE under German formulation standards.",
    materialsInfo: "Jojoba Oil, Vitamin E, Light moisturizing emulsion.",
    dimensionsInfo: "200ml White Tub.",
    capacityInfo: "200ml.",
    careInfo: "Smooth onto clean face, hands, or dry elbows whenever needed.",
    basePrice: 800,
    compareAtPrice: 950,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "creams",
    collections: ["winter-hydration"],
    tags: ["nivea", "nivea-soft", "cream", "moisturizer", "bestseller"],
    rating: 4.8,
    reviewCount: 52,
    isBestseller: true,
    primaryImage: "https://valobazar.com/storage/products/wJw6P4tqT0TuOh2LHrPWNDfhKyHQ7Xg7wmrRdxMl.jpg",
    hoverImage: "https://valobazar.com/storage/products/wJw6P4tqT0TuOh2LHrPWNDfhKyHQ7Xg7wmrRdxMl.jpg",
    images: ["https://valobazar.com/storage/products/wJw6P4tqT0TuOh2LHrPWNDfhKyHQ7Xg7wmrRdxMl.jpg"],
    variants: [
      {
        id: "v_nivea_200",
        sku: "NIV-SOFT-200ML",
        title: "Nivea Soft 200ml",
        colorName: "Clean White Tub",
        colorHex: "#FFFFFF",
        price: 800,
        compareAtPrice: 950,
        inventory: 60,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/wJw6P4tqT0TuOh2LHrPWNDfhKyHQ7Xg7wmrRdxMl.jpg"],
      },
    ],
    reviews: [],
  },
  {
    id: "prod_skin_vaseline_jelly100",
    slug: "vaseline-moisturizing-pure-jelly-100ml",
    name: "Vaseline Pure Petroleum Jelly Original 100ml",
    subtitle: "Triple-Purified Skin Protecting Barrier Ointment",
    description: "The original triple-purified wonder jelly. Locks in moisture to help heal dry, cracked winter skin, soothe minor scrapes, chapped lips, and rough heels.",
    details: "Volume: 100ml. 100% pure triple-purified white petrolatum.",
    materialsInfo: "White Petrolatum USP (100%).",
    dimensionsInfo: "100ml Tub.",
    capacityInfo: "100ml.",
    careInfo: "Scoop with fingertips and apply to dry lips, hands, and feet.",
    basePrice: 450,
    compareAtPrice: 550,
    currency: "BDT",
    categorySlug: "herbal-skincare",
    categoryName: "Herbal & Winter Skin Care",
    subcategorySlug: "creams",
    collections: ["winter-hydration"],
    tags: ["vaseline", "petroleum-jelly", "lip-care", "winter-essential"],
    rating: 4.9,
    reviewCount: 40,
    isBestseller: false,
    primaryImage: "https://valobazar.com/storage/products/Q28Kx0BTNI51RrvACNQq5mrqLFxjKE7UWmd9EQ36.jpg",
    hoverImage: "https://valobazar.com/storage/products/Q28Kx0BTNI51RrvACNQq5mrqLFxjKE7UWmd9EQ36.jpg",
    images: ["https://valobazar.com/storage/products/Q28Kx0BTNI51RrvACNQq5mrqLFxjKE7UWmd9EQ36.jpg"],
    variants: [
      {
        id: "v_vas_jelly_100",
        sku: "VAS-JELLY-100ML",
        title: "Vaseline Jelly 100ml",
        colorName: "Clear Blue Cap",
        colorHex: "#2563EB",
        price: 450,
        compareAtPrice: 550,
        inventory: 80,
        isDefault: true,
        images: ["https://valobazar.com/storage/products/Q28Kx0BTNI51RrvACNQq5mrqLFxjKE7UWmd9EQ36.jpg"],
      },
    ],
    reviews: [],
  },
];

// Helper queries
export function getAllProducts(): ProductItem[] {
  return PRODUCTS;
}

export function getProductBySlug(slug: string): ProductItem | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string, subcategorySlug?: string): ProductItem[] {
  return PRODUCTS.filter((p) => {
    if (categorySlug === "featured") return true;
    if (p.categorySlug !== categorySlug) return false;
    if (subcategorySlug && p.subcategorySlug !== subcategorySlug) return false;
    return true;
  });
}

export function getProductsByCollection(collectionSlug: string): ProductItem[] {
  const col = COLLECTIONS.find((c) => c.slug === collectionSlug);
  if (!col) return [];
  return PRODUCTS.filter((p) => col.productSlugs.includes(p.slug) || p.collections.includes(collectionSlug));
}

export function searchProducts(query: string): ProductItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.subtitle.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.categoryName.toLowerCase().includes(q)
  );
}